### ISSUE TITLE
Are we sure node failure isn't correlated?

### ISSUE THREAD

**Issue by retrohacker** [storj/whitepaper#11]
Is this substantiated?

https://github.com/Storj/whitepaper/blob/master/Storj%20Whitepaper%20V2.tex#L58

> Because peers generally rely on separate hardware and infrastructure, data failure is not correlated

**Comment by RichardLitt** [comment]
This work is being continued in our forthcoming whitepaper. Follow along at [storj/storj](https://github.com/storj/storj).
