### ISSUE TITLE
[WIP] v2.1 plans

### ISSUE THREAD

**Issue by prestwich** [storj/whitepaper#29]
- [ ] Add graphic for Offer Loop
- [ ] Add graphic for Quasar Loop

**Comment by frdwrd** [comment]
[ ] - Clarify data owner/renter/bridge/client/etc responsibilities. Maybe a table showing how they're split.

**Comment by RichardLitt** [comment]
This work is being continued in our forthcoming whitepaper. Follow along at [storj/storj](https://github.com/storj/storj).
