### ISSUE TITLE
Unclear sentence in Payments

### ISSUE THREAD

**Issue by RNabel** [Storj/whitepaper#32]
Section 2.5 (Payments) "Micropayment networks, like the Lightning Network, Implementation details of other payment strategies are left as an exercise for interested parties."

The sentence doesn't make sense - what exactly was the intention? It is most likely that networks like the `Lightning Network` are viable alternatives to Storjcoin, in which case just a few words are missing.

**Comment by frdwrd** [comment]
I have a nasty habit of jumping back and forth between sentences while writing. I started one, and then left it half-finished.

Fixed in ad48bef.

```
Micropayment networks, like the Lightning Network \cite{25}, solve many of these problems, and are thus an ideal candidate for future payment strategies.```
